@hostname = http://localhost:8080
@contents-json = Content-Type: application/json; charset=utf-8

### get

GET http://localhost:8080/user


### post

POST http://localhost:8080/user
{{contents-json}}

{
  "name" : "kurore33",
  "password" : "kuroPassword",
  "email": "hogehoge@gmail.com"
}

### delete

DELETE  {{hostname}}/user/2
